import { NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'

export async function GET() {
  try {
    const settings = await prisma.settings.findUnique({
      where: { id: 'default' },
    })

    if (!settings) {
      return NextResponse.json({
        siteName: 'Beauty Studio',
        colorPrimary: '#c4367b',
        colorSecondary: '#f5dbe8',
        colorButton: '#aa1d68',
        fontFamily: 'Inter',
        heroBannerUrl: null,
        enableCart: true,
        headingFontSize: '32px',
        bodyFontSize: '16px',
        smallFontSize: '14px',
        logoUrl: null,
        faviconUrl: null,
        whatsappNumber: null,
        email: null,
        address: null,
        socialLinks: {},
        gaTrackingId: null,
        operatingHours: {
          Sunday: 'Closed',
          Monday: '10:00 - 21:00',
          Tuesday: '10:00 - 21:00',
          Wednesday: '10:00 - 21:00',
          Thursday: '10:00 - 21:00',
          Friday: '10:00 - 21:00',
          Saturday: '10:00 - 16:00',
        },
        heroBadge: '⭐ Premium Beauty Services',
        heroSubtitle: 'Discover premium beauty services and products for your perfect look',
        heroShopButtonText: 'Shop Now',
        heroShopButtonLink: '/products',
        heroBookButtonText: 'Book Now',
        heroBookButtonLink: '/booking',
        heroSlide1Icon: '🔥',
        heroSlide1Label: 'Limited Time Offer',
        heroSlide1Title: 'FLASH SALE 50% OFF',
        heroSlide1Desc: 'Grab your favorite products at unbeatable prices',
        heroSlide1Button: 'Grab Now',
        heroSlide1Link: '/products',
        heroSlide1BgStart: '#f97316',
        heroSlide1BgEnd: '#db2777',
        heroSlide2Icon: '📅',
        heroSlide2Label: 'Book Now & Get Special Offer',
        heroSlide2Title: 'FREE Consultation',
        heroSlide2Desc: 'Book your appointment today and get free consultation',
        heroSlide2Button: 'Book Now',
        heroSlide2Link: '/booking',
        heroSlide2BgStart: '#8b5cf6',
        heroSlide2BgEnd: '#ec4899',
        aboutHeroTitle: 'About Us',
        aboutHeroSubtitle: 'Learn more about our journey',
        aboutStoryTitle: 'Our Story',
        aboutStoryContent: 'We are passionate about bringing beauty to everyone...',
        aboutMission: 'To bring beauty and confidence to every individual',
        aboutVision: 'To be the leading beauty destination in the region',
        aboutTeamTitle: 'Meet Our Team',
        aboutTeam: null,
        contactHeroTitle: 'Contact Us',
        contactHeroSubtitle: "We'd love to hear from you",
        contactFormTitle: 'Send Us a Message',
        contactSuccessMessage: 'Thank you for your message! We will get back to you soon.',
      })
    }

    return NextResponse.json({
      siteName: settings.siteName,
      colorPrimary: settings.colorPrimary,
      colorSecondary: settings.colorSecondary,
      colorButton: settings.colorButton,
      fontFamily: settings.fontFamily,
      heroBannerUrl: settings.heroBannerUrl,
      enableCart: settings.enableCart,
      headingFontSize: settings.headingFontSize,
      bodyFontSize: settings.bodyFontSize,
      smallFontSize: settings.smallFontSize,
      logoUrl: settings.logoUrl,
      faviconUrl: settings.faviconUrl,
      whatsappNumber: settings.whatsappNumber,
      email: settings.email,
      address: settings.address,
      socialLinks: settings.socialLinks,
      gaTrackingId: settings.gaTrackingId,
      // 🔥 TAMBAHKAN OPERATING HOURS
      operatingHours: settings.operatingHours || {
        Sunday: 'Closed',
        Monday: '10:00 - 21:00',
        Tuesday: '10:00 - 21:00',
        Wednesday: '10:00 - 21:00',
        Thursday: '10:00 - 21:00',
        Friday: '10:00 - 21:00',
        Saturday: '10:00 - 16:00',
      },
      heroBadge: settings.heroBadge,
      heroSubtitle: settings.heroSubtitle,
      heroShopButtonText: settings.heroShopButtonText,
      heroShopButtonLink: settings.heroShopButtonLink,
      heroBookButtonText: settings.heroBookButtonText,
      heroBookButtonLink: settings.heroBookButtonLink,
      heroSlide1Icon: settings.heroSlide1Icon,
      heroSlide1Label: settings.heroSlide1Label,
      heroSlide1Title: settings.heroSlide1Title,
      heroSlide1Desc: settings.heroSlide1Desc,
      heroSlide1Button: settings.heroSlide1Button,
      heroSlide1Link: settings.heroSlide1Link,
      heroSlide1BgStart: settings.heroSlide1BgStart,
      heroSlide1BgEnd: settings.heroSlide1BgEnd,
      heroSlide2Icon: settings.heroSlide2Icon,
      heroSlide2Label: settings.heroSlide2Label,
      heroSlide2Title: settings.heroSlide2Title,
      heroSlide2Desc: settings.heroSlide2Desc,
      heroSlide2Button: settings.heroSlide2Button,
      heroSlide2Link: settings.heroSlide2Link,
      heroSlide2BgStart: settings.heroSlide2BgStart,
      heroSlide2BgEnd: settings.heroSlide2BgEnd,
      aboutHeroTitle: settings.aboutHeroTitle,
      aboutHeroSubtitle: settings.aboutHeroSubtitle,
      aboutStoryTitle: settings.aboutStoryTitle,
      aboutStoryContent: settings.aboutStoryContent,
      aboutMission: settings.aboutMission,
      aboutVision: settings.aboutVision,
      aboutTeamTitle: settings.aboutTeamTitle,
      aboutTeam: settings.aboutTeam,
      contactHeroTitle: settings.contactHeroTitle,
      contactHeroSubtitle: settings.contactHeroSubtitle,
      contactFormTitle: settings.contactFormTitle,
      contactSuccessMessage: settings.contactSuccessMessage,
    })
  } catch (error) {
    console.error('Error fetching settings:', error)
    return NextResponse.json({
      siteName: 'Beauty Studio',
      colorPrimary: '#c4367b',
      colorSecondary: '#f5dbe8',
      colorButton: '#aa1d68',
      fontFamily: 'Inter',
      heroBannerUrl: null,
      enableCart: true,
      headingFontSize: '32px',
      bodyFontSize: '16px',
      smallFontSize: '14px',
      logoUrl: null,
      faviconUrl: null,
      whatsappNumber: null,
      email: null,
      address: null,
      socialLinks: {},
      gaTrackingId: null,
      operatingHours: {
        Sunday: 'Closed',
        Monday: '10:00 - 21:00',
        Tuesday: '10:00 - 21:00',
        Wednesday: '10:00 - 21:00',
        Thursday: '10:00 - 21:00',
        Friday: '10:00 - 21:00',
        Saturday: '10:00 - 16:00',
      },
      heroBadge: '⭐ Premium Beauty Services',
      heroSubtitle: 'Discover premium beauty services and products for your perfect look',
      heroShopButtonText: 'Shop Now',
      heroShopButtonLink: '/products',
      heroBookButtonText: 'Book Now',
      heroBookButtonLink: '/booking',
      heroSlide1Icon: '🔥',
      heroSlide1Label: 'Limited Time Offer',
      heroSlide1Title: 'FLASH SALE 50% OFF',
      heroSlide1Desc: 'Grab your favorite products at unbeatable prices',
      heroSlide1Button: 'Grab Now',
      heroSlide1Link: '/products',
      heroSlide1BgStart: '#f97316',
      heroSlide1BgEnd: '#db2777',
      heroSlide2Icon: '📅',
      heroSlide2Label: 'Book Now & Get Special Offer',
      heroSlide2Title: 'FREE Consultation',
      heroSlide2Desc: 'Book your appointment today and get free consultation',
      heroSlide2Button: 'Book Now',
      heroSlide2Link: '/booking',
      heroSlide2BgStart: '#8b5cf6',
      heroSlide2BgEnd: '#ec4899',
      aboutHeroTitle: 'About Us',
      aboutHeroSubtitle: 'Learn more about our journey',
      aboutStoryTitle: 'Our Story',
      aboutStoryContent: 'We are passionate about bringing beauty to everyone...',
      aboutMission: 'To bring beauty and confidence to every individual',
      aboutVision: 'To be the leading beauty destination in the region',
      aboutTeamTitle: 'Meet Our Team',
      aboutTeam: null,
      contactHeroTitle: 'Contact Us',
      contactHeroSubtitle: "We'd love to hear from you",
      contactFormTitle: 'Send Us a Message',
      contactSuccessMessage: 'Thank you for your message! We will get back to you soon.',
    })
  }
}